exports.seed = function (knex) {
  return knex("answers_cards")
    .del()
    .then(function () {
      return knex("answers_cards").insert([
        { id: 1, type: "ANSWER", card_text: "Figę z makiem" },
        { id: 2, type: "ANSWER", card_text: "Wycieczka do lasu w bagażniku" },
        {
          id: 3,
          type: "ANSWER",
          card_text: "Twarz, którą pokocha jedynie matka",
        },
        {
          id: 4,
          type: "ANSWER",
          card_text: "Średnio udana terapia hormonalna",
        },
        { id: 5, type: "ANSWER", card_text: "Samobójstwo z ciekawości" },
        { id: 6, type: "ANSWER", card_text: "Studia bez perspektyw" },
        { id: 7, type: "ANSWER", card_text: "Donald Tusk" },
        {
          id: 8,
          type: "ANSWER",
          card_text: "Donald Tusk wyżej w tabeli ligowej niż Legia Warszawa",
        },
        { id: 9, type: "ANSWER", card_text: "Niesrogi autyzm" },
        {
          id: 10,
          type: "ANSWER",
          card_text: "Stowarzyszenie amatorów nieletnich ciał",
        },
        { id: 11, type: "ANSWER", card_text: "Żółty śnieg" },
        { id: 12, type: "ANSWER", card_text: "Allah" },
        { id: 13, type: "ANSWER", card_text: "Wypełnianie PIT-u" },
        { id: 14, type: "ANSWER", card_text: "Brzydkie koleżanki" },
        {
          id: 15,
          type: "ANSWER",
          card_text: "Bycie jedyną białą samicą w barze pełnym erasmusów",
        },
        { id: 16, type: "ANSWER", card_text: "Buty na rzepy" },
        {
          id: 17,
          type: "ANSWER",
          card_text: "Związki zawodowe pracownikó fabryk gadżetów erotycznych",
        },
        { id: 18, type: "ANSWER", card_text: "Trzy" },
        { id: 19, type: "ANSWER", card_text: "Cztery" },
        { id: 20, type: "ANSWER", card_text: "Może wrzesień" },
        { id: 21, type: "ANSWER", card_text: "Cios w szczepionkę" },
        {
          id: 22,
          type: "ANSWER",
          card_text: "Zwalnianie pracownikó za pomocą katapulty",
        },
        { id: 23, type: "ANSWER", card_text: "Student abstynent" },
        { id: 24, type: "ANSWER", card_text: "Chłostanie byka" },
        { id: 25, type: "ANSWER", card_text: "Dobór naturalny" },
        { id: 26, type: "ANSWER", card_text: "Selekcja naturalna" },
        { id: 27, type: "ANSWER", card_text: "Jarosław Kaczyński" },
        { id: 28, type: "ANSWER", card_text: "Marek Suski" },
        { id: 29, type: "ANSWER", card_text: "Czopki z gwintem" },
        { id: 30, type: "ANSWER", card_text: "Zbrodnie wojenne" },
        { id: 31, type: "ANSWER", card_text: "Cygańskie biznesy" },
        { id: 32, type: "ANSWER", card_text: "Zdrajca rasy" },
        { id: 33, type: "ANSWER", card_text: "Drużyna Actimela" },
        { id: 34, type: "ANSWER", card_text: "Dobre drogi w Łodzi" },
        { id: 35, type: "ANSWER", card_text: "Szybki jak PKP" },
        {
          id: 36,
          type: "ANSWER",
          card_text: "Dosypywanie Viagry do kaszek dla niemowląt",
        },
        { id: 37, type: "ANSWER", card_text: "Doktorat z socjologii" },
        { id: 38, type: "ANSWER", card_text: "Gender" },
        { id: 39, type: "ANSWER", card_text: "Epidemia covid" },
        { id: 40, type: "ANSWER", card_text: "kredyt na wesele" },
        {
          id: 41,
          type: "ANSWER",
          card_text: "Bonifikarta na opłaty w dziekanacie",
        },
        { id: 42, type: "ANSWER", card_text: "Grube dziewczyny w leginsach" },
        { id: 43, type: "ANSWER", card_text: "Ilustrowany atlas pestycydów" },
        { id: 44, type: "ANSWER", card_text: "Ziemniak" },
        { id: 45, type: "ANSWER", card_text: "Jagodzianki z truskawkami" },
        {
          id: 46,
          type: "ANSWER",
          card_text: "Zespół napięcia przedmiesiączkowego",
        },
        { id: 47, type: "ANSWER", card_text: "Pabianicka pieśń patriotyczna" },
        { id: 48, type: "ANSWER", card_text: "Kierowcy BMW" },
        { id: 49, type: "ANSWER", card_text: "Duj w słupie, słój w d" },
        { id: 50, type: "ANSWER", card_text: "Konserwant E 953" },
        { id: 51, type: "ANSWER", card_text: "To nie był prawdziwy komunizm" },
        { id: 52, type: "ANSWER", card_text: "Logicznie myśląca kobieta" },
        { id: 53, type: "ANSWER", card_text: "Wyjściowy dres" },
        { id: 54, type: "ANSWER", card_text: "Kardynał Dziwisz wiedział" },
        { id: 55, type: "ANSWER", card_text: "Kardynał Dziwisz nie wiedział" },
        { id: 56, type: "ANSWER", card_text: "Jasełka w KGB" },
        { id: 57, type: "ANSWER", card_text: "Makao na śmierć i życie" },
        { id: 58, type: "ANSWER", card_text: "Niewolnictwo fair trade" },
        { id: 59, type: "ANSWER", card_text: "Niewolnictwa niska cena" },
        { id: 60, type: "ANSWER", card_text: "Moja była" },
        { id: 61, type: "ANSWER", card_text: "Musztarda bez akcyzy" },
        { id: 62, type: "ANSWER", card_text: "SQL injection" },
        { id: 63, type: "ANSWER", card_text: "Parafia pw. Bedoesa SBM" },
        { id: 64, type: "ANSWER", card_text: "Niemcy zazdroszczący polakom" },
        { id: 65, type: "ANSWER", card_text: "Orgie drwali" },
        { id: 66, type: "ANSWER", card_text: "Owoce Jogobelli" },
        { id: 67, type: "ANSWER", card_text: "Jeszcze jak" },
        { id: 68, type: "ANSWER", card_text: "Tak Pan Jezus powiedział" },
        { id: 69, type: "ANSWER", card_text: "Jurij Owsiakov" },
        { id: 70, type: "ANSWER", card_text: "Sosnowiec" },
        { id: 71, type: "ANSWER", card_text: "Rasowo czysta europa" },
        { id: 72, type: "ANSWER", card_text: "Rasista daltonista" },
        { id: 73, type: "ANSWER", card_text: "Radioaktywni grzybiarze" },
        { id: 74, type: "ANSWER", card_text: "Przyjaźń damsko-męska" },
        { id: 75, type: "ANSWER", card_text: "Czyszczenie mebli Kukizem" },
        {
          id: 76,
          type: "ANSWER",
          card_text: "Przegłosowanie kolejnego rozbioru Polski",
        },
        { id: 77, type: "ANSWER", card_text: "Rwanie na dywanie" },
        { id: 78, type: "ANSWER", card_text: "Sandały z azbestu" },
        { id: 79, type: "ANSWER", card_text: "Seryjny samobójca" },
        { id: 80, type: "ANSWER", card_text: "Uran czeczenom" },
        { id: 81, type: "ANSWER", card_text: "Spawacz-ginekolog" },
        { id: 82, type: "ANSWER", card_text: "Ciche dni" },
        { id: 83, type: "ANSWER", card_text: "95-minutowy kwadrans studencki" },
        { id: 84, type: "ANSWER", card_text: "Protokół HTTP" },
        { id: 85, type: "ANSWER", card_text: "Protokół TCL" },
        {
          id: 86,
          type: "ANSWER",
          card_text: "Obieranie cebuli i programowanie w javascript",
        },
        { id: 87, type: "ANSWER", card_text: "Javascript" },
        { id: 88, type: "ANSWER", card_text: " '1' + '1' = '11' " },
        { id: 89, type: "ANSWER", card_text: "Piętnasta dawka" },
        { id: 90, type: "ANSWER", card_text: "750 tysięcy zakażeń" },
        {
          id: 91,
          type: "ANSWER",
          card_text:
            "Wytwórnia niskogatunkowych wyrobów alkoholowych 'Akademik'",
        },
        { id: 92, type: "ANSWER", card_text: "Szpitalne żarcie" },
        {
          id: 93,
          type: "ANSWER",
          card_text: "Ta dziwna zabawa w zapasy z wujkiem Staszkiem",
        },
        { id: 94, type: "ANSWER", card_text: "Śląscy naukowcy" },
        { id: 95, type: "ANSWER", card_text: "Donald Trump" },
        { id: 96, type: "ANSWER", card_text: "Orange President" },
        { id: 97, type: "ANSWER", card_text: "Wichajster" },
        { id: 98, type: "ANSWER", card_text: "Ten-teges" },
        {
          id: 99,
          type: "ANSWER",
          card_text: "Udany jak premiera Cyberpunka 2077",
        },
        { id: 100, type: "ANSWER", card_text: "Polski Ład" },
      ]);
    });
};
